---
name: pipeline

on:
  pull_request:
  push:
    branches: [main]

env:
  CC: /usr/bin/clang
  CXX: /usr/bin/clang++

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Toolchain Version
        run: |
          bazel --version
          $CXX --version

      - name: Build
        run: bazel build //:playground

      - name: Test
        run: bazel run  //:playground
